version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  frontend:
    build: ./frontend
    container_name: next_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app
    command: "npm run dev"
    working_dir: /app

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  db_data: